-- 创建需求悬赏表
CREATE TABLE public.demands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  requester TEXT NOT NULL,
  department TEXT,
  budget TEXT NOT NULL,
  deadline DATE NOT NULL,
  tags TEXT[] DEFAULT '{}',
  status TEXT DEFAULT '招募中' CHECK (status IN ('招募中', '进行中', '已完成', '已取消')),
  applicants_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 创建需求申请表
CREATE TABLE public.demand_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  demand_id BIGINT REFERENCES public.demands(id) ON DELETE CASCADE,
  applicant_name TEXT NOT NULL,
  applicant_email TEXT,
  proposal TEXT,
  status TEXT DEFAULT '待审核' CHECK (status IN ('待审核', '已通过', '已拒绝')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.demands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_applications ENABLE ROW LEVEL SECURITY;

-- 允许任何人读取需求列表
CREATE POLICY "Allow public read access for demands" ON public.demands
  FOR SELECT USING (true);

-- 允许任何人创建需求
CREATE POLICY "Allow public insert access for demands" ON public.demands
  FOR INSERT WITH CHECK (true);

-- 允许任何人读取需求申请
CREATE POLICY "Allow public read access for applications" ON public.demand_applications
  FOR SELECT USING (true);

-- 允许任何人创建需求申请
CREATE POLICY "Allow public insert access for applications" ON public.demand_applications
  FOR INSERT WITH CHECK (true);

-- 创建触发器自动更新 updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_demands_updated_at
  BEFORE UPDATE ON public.demands
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 创建触发器自动更新申请数量
CREATE OR REPLACE FUNCTION update_applicants_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.demands
    SET applicants_count = applicants_count + 1
    WHERE id = NEW.demand_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.demands
    SET applicants_count = applicants_count - 1
    WHERE id = OLD.demand_id;
  END IF;
  RETURN NULL;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_applicants_count_insert
  AFTER INSERT ON public.demand_applications
  FOR EACH ROW
  EXECUTE FUNCTION update_applicants_count();

CREATE TRIGGER update_applicants_count_delete
  AFTER DELETE ON public.demand_applications
  FOR EACH ROW
  EXECUTE FUNCTION update_applicants_count();