-- 创建最佳实践表
CREATE TABLE public.best_practices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  views INT DEFAULT 0,
  likes INT DEFAULT 0,
  tags TEXT[] DEFAULT '{}',
  content TEXT NOT NULL,
  prompt TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.best_practices ENABLE ROW LEVEL SECURITY;

-- 允许任何人读取最佳实践列表
CREATE POLICY "Allow public read access" ON public.best_practices
  FOR SELECT USING (true);
